---

- hosts: all
  become: true
  tasks:
  - name: Update and Upgrade apt packages on Debian_Ubuntu servers  
    apt:
      update_cache: yes
      upgrade: dist


  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 
  
  - name: add php support for apache
    apt: 
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian" or ansible_distribution == 'Ubuntu' 
