---

- hosts: all
  become: true
  tasks:

  - name: Update and Upgrade Debian_Ubuntu servers
    apt:
      update_cache: yes
      upgrade: dist


  - name: Install apache and php
    package: 
      name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
      state: latest
