---

- hosts: all
  become: true
  tasks:
  - name: Update and Upgrade apt packages on Debian_Ubuntu servers  
    apt:
      update_cache: yes
      upgrade: dist
#   when: ansible_distrubution == "Ubuntu" -----> a better way below - we use 'IN' instead of the equal sign if we want to use > than one 
    when: ansible_distrbution in ["Ubuntu", "Debian"] 


  - name: install apache2 package
    apt:
      name: apache2
      state: latest
#    when: ansible_distribution == "Ubuntu"
     when: ansible_distrbution in ["Ubuntu", "Debian"]
  
  - name: add php support for apache
    apt: 
      name: libapache2-mod-php
      state: latest
   #when: ansible_distribution == "Debian" 
    when: ansible_distrbution in ["Ubuntu", "Debian"]
